# Generated by Django 5.2.12 on 2026-03-05 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=1)),
                ('imagepath', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
