# Generated by Django 5.2.12 on 2026-03-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_products_imagepath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='dept_id',
            new_name='department',
        ),
    ]
