# Generated by Django 6.0.3 on 2026-03-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_dept_id_students_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(default=1)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'db_table': 'order_confirmation',
            },
        ),
        migrations.CreateModel(
            name='Order_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=1)),
                ('gst_per', models.IntegerField()),
                ('gst_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('order_confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.order_conf')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.products')),
            ],
            options={
                'db_table': 'order_products',
            },
        ),
    ]
