# Generated by Django 6.0.3 on 2026-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_conf_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_conf',
            name='gst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order_conf',
            name='net_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order_conf',
            name='total_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
