# Generated by Django 6.0.3 on 2026-03-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_order_conf_gst_amt_alter_order_conf_net_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_products',
            name='product_count',
            field=models.IntegerField(default=1),
        ),
    ]
