# Generated by Django 6.0.3 on 2026-03-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_order_products_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_products',
            name='product_count',
        ),
        migrations.AddField(
            model_name='order_conf',
            name='product_count',
            field=models.IntegerField(default=1),
        ),
    ]
